Repository liquality/collective-frames, pull requests merged in 2024-04, with the labels that each got.

#3 Feat/johanna db stuff
  README.md
  env-example
  src/app/api/frames/route.ts
  src/app/components/Navbar.tsx
  src/app/components/UploadForm.tsx
  src/db/migrate.ts
  src/db/migrations/0000_shallow_phalanx.sql
  src/db/migrations/0001_naive_joseph.sql
  src/db/migrations/meta/0000_snapshot.json
  src/db/migrations/meta/0001_snapshot.json
  src/db/migrations/meta/_journal.json
  src/db/schema.ts
  src/utils/nft.ts
Labels: 🔍 Ready for Review, size/L

#4 Feat/zora
  env-example
  package-lock.json
  package.json
  src/app/api/frames/route.ts
  src/app/components/CopyModal.tsx
  src/app/components/UploadForm.tsx
  src/types.ts
  src/utils/nft.ts
  tsconfig.json
Labels: 🔍 Ready for Review, size/L

#5 feat: take data from database to render mint frame
  src/app/api/collectives/route.ts
  src/app/api/frames/route.ts
  src/app/components/CopyModal.tsx
  src/app/components/CreateFrame.css
  src/app/components/CreateFrame.tsx
  src/app/components/DragNdropFile.css
  src/app/components/DragNdropFile.tsx
  src/app/components/Login.tsx
  src/app/components/Navbar.tsx
  src/app/components/NeynarButton.tsx
  src/app/components/UploadForm.tsx
  src/app/frames/[frameId]/route.tsx
  src/app/page.tsx
  src/context/AppContext.tsx
  src/db/db.ts
  src/db/migrate.ts
Labels: ✅ Approved, size/XL

#9 feat: changed to use neynar client to find user address
  src/middleware.ts
  src/utils/neynar.ts
  src/utils/user.ts
Labels: 🔍 Ready for Review, size/M

#10 Feat/johanna design
  package-lock.json
  public/sdk_logo.png
  src/app/components/CreateFrame.tsx
  src/app/components/Navbar.tsx
  src/app/components/OurVision.tsx
  src/app/globals.css
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/share/[id]/page.tsx
  tailwind.config.ts
Labels: 🔍 Ready for Review, size/L

#11 Feat/johanna design
  package-lock.json
  package.json
  public/sdk_logo.svg
  src/app/components/Footer.tsx
  src/app/components/OurVision.tsx
  src/app/layout.tsx
  src/app/share/[id]/page.tsx
Labels: 🔍 Ready for Review, size/L

#12 Feat/johanna design
  env-example
  src/app/components/CopyModal.tsx
  src/app/components/Footer.tsx
  src/app/components/OurVision.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/share/[id]/page.tsx
  src/middleware.ts
Labels: size/S

#13 Feat/farcaster auth kit
  package-lock.json
  package.json
  src/app/api/user/route.ts
  src/app/components/CopyModal.tsx
  src/app/components/CreateFrame.tsx
  src/app/components/FarcasterLogin.tsx
  src/app/components/FarcasterSigninButton.tsx
  src/app/components/Modal.tsx
  src/app/components/Navbar.tsx
  src/app/components/NeynarLogin.tsx
  src/app/frames/[frameId]/route.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/context/AppContext.tsx
  src/db/migrations/0004_dark_rhino.sql
  src/db/migrations/meta/0004_snapshot.json
  src/db/migrations/meta/_journal.json
  src/db/schema.ts
  src/hooks/useGetUserByFid.tsx
  src/middleware.ts
  src/types.ts
  src/utils/api-service.ts
  src/utils/cookie-auth.ts
  src/utils/neynar.ts
Labels: 🔍 Ready for Review, size/XL

#14 feat: addec custom signin modal and middleware / navigation
  src/app/api/frames/route.ts
  src/app/components/FarcasterLogin.tsx
  src/app/components/FarcasterSigninButton.tsx
  src/app/components/Modal.tsx
  src/app/components/Navbar.tsx
  src/app/components/OurVision.tsx
  src/app/create-frame/page.tsx
  src/app/dashboard/page.tsx
  src/app/frames/[frameId]/route.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/share/[id]/page.tsx
  src/middleware.ts
  src/utils/api-service.ts
Labels: 🔍 Ready for Review, size/L

#15 Feat/resize image
  package-lock.json
  package.json
  src/app/components/DragNdropFile.tsx
  src/middleware.ts
Labels: size/L

#16 Feat/share on warpcast
  src/app/components/CopyModal.tsx
Labels: size/S

#18 Feat/transaction
  src/app/api/create/[id]/route.ts
  src/app/api/create/route.ts
  src/app/api/user/[id]/route.tsx
  src/app/components/CreateFrame.tsx
  src/app/dashboard/page.tsx
  src/app/frames-transaction/[slug]/page.tsx
  src/app/frames-transaction/contract-abi.ts
  src/app/frames-transaction/frames/route.tsx
  src/app/frames-transaction/txdata/[slug]/route.tsx
  src/app/frames/[frameId]/route.tsx
  src/utils/api-service.ts
  src/utils/frame.ts
Labels: size/XXL

#19 Feat/refactor mint frontend params
  src/app/api/collectives/route.ts
  src/app/api/collectives/route.tsx
  src/app/api/create/route.ts
  src/app/components/CreateFrame.tsx
  src/app/share/[id]/page.tsx
  src/constants/erc20-token-data.ts
  src/db/migrations/0002_unknown_paper_doll.sql
  src/db/migrations/meta/0002_snapshot.json
  src/db/migrations/meta/_journal.json
  src/db/schema.ts
  src/db/testdata.sql
  src/utils/collective.ts
  src/utils/constants.ts
  src/utils/frame.ts
  src/utils/nft.ts
Labels: 🔍 Ready for Review, size/XXL

#20 Fix: error with createHonneyPot
  src/app/api/collectives/route.ts
  src/utils/constants.ts
Labels: 🔍 Ready for Review, size/M

#21 run migrations and new column in collective db table
  src/app/frames-transaction/txdata/[slug]/route.tsx
  src/db/migrations/0004_deep_golden_guardian.sql
  src/db/migrations/meta/0004_snapshot.json
  src/db/migrations/meta/_journal.json
  src/db/schema.ts
  src/db/testdata.sql
Labels: 🔍 Ready for Review, size/M

#22 Chore: Breakdown mint flow into two phases for ERC20Mints
  src/types.ts
  src/utils/nft.ts
Labels: 🔍 Ready for Review, size/M

#24 Feat/design impl
  public/favicon-32x32.png
  public/main-bg-mobile.png
  public/main-bg.png
  src/app/api/create/route.ts
  src/app/components/CreateFrame.tsx
  src/app/components/Footer.tsx
  src/app/components/Navbar.tsx
  src/app/components/OurVision.tsx
  src/app/create-frame/page.tsx
  src/app/dashboard/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/app/share/[id]/page.tsx
Labels: size/XL

#25 Feat/fix totalvalue
  src/app/api/create/route.ts
  src/app/api/user/route.ts
  src/app/components/CreateFrame.tsx
  src/app/frames-transaction/[slug]/route.tsx
  src/app/frames-transaction/txdata/[slug]/premint/route.tsx
  src/app/frames-transaction/txdata/[slug]/route.tsx
  src/constants/erc20-token-data.ts
  src/db/schema.ts
  src/hooks/useGetExchangePrice.tsx
  src/types.ts
  src/utils/constants.ts
  src/utils/helpers.ts
  src/utils/nft.ts
  src/utils/user.ts
  tsconfig.json
Labels: size/L

#27 Fix/UI fixes
  src/app/components/FarcasterSigninButton.tsx
  src/app/components/Footer.tsx
  src/app/components/Navbar.tsx
  src/app/components/OurVision.tsx
  src/app/layout.tsx
  src/app/page.tsx
Labels: size/L

#29 Chore clean up
  src/app/api/collectives/route.ts
  src/app/api/mint/route.ts
  src/app/api/rewards/route.ts
  src/utils/collective.ts
  src/utils/constants.ts
  src/utils/nft.ts
Labels: 🔍 Ready for Review, size/XXL

#31 fix: fixed dashbaord list and share img styles
  src/app/dashboard/page.tsx
  src/app/share/[id]/page.tsx
Labels: 🔍 Ready for Review, size/S

#32 Fix: Resolve error with maxFeePerGas below block fee
  src/app/api/mint/route.ts
  src/types.ts
  src/utils/nft.ts
Labels: 🔍 Ready for Review, size/L

#33 Fix/UI
  src/app/components/CopyModal.tsx
  src/app/components/CreateFrame.tsx
  src/app/layout.tsx
  src/app/share/[id]/page.tsx
Labels: size/M
